project_id = "rnsgxjgocgguyybyggem"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1"

[functions.generate-comment]
verify_jwt = false

[functions.chat]
verify_jwt = false

[functions.generate-food-image]
verify_jwt = false

[functions.vibecheck]
verify_jwt = false